<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Where's the party ?</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700' rel='stylesheet' type='text/css'>

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places,visualization&sensor=true"></script>
    <script src='https://cdn.firebase.com/js/client/1.1.1/firebase.js'></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="/media/css/desktop/main.css" media="screen"/>

    <script src="/media/js/desktop/map.js"></script>
    <script src="/media/js/desktop/heat.map.js"></script>
    <script src="/media/js/desktop/current.location.js"></script>
    <script src="/media/js/desktop/main.js"></script>
</head>
<body>