<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places,visualization&sensor=true"></script>
<script src='https://cdn.firebase.com/js/client/1.1.1/firebase.js'></script>

<script src="/media/js/mobile/tutorial.js"></script>

<script src="/media/js/mobile/bxslider.js"></script>
<script src="/media/js/mobile/map.js"></script>
<script src="/media/js/mobile/heat.map.js"></script>
<script src="/media/js/mobile/current.location.js"></script>
<script src="/media/js/mobile/awesome.button.js"></script>
<script src="/media/js/mobile/main.js"></script>

</body>
</html>