<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Where's the party ?</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700' rel='stylesheet' type='text/css'>

    <!-- Favicon-->
    <link href="media/images/mobile/icon-57.png" rel="shortcut icon">
    <!-- iOS 7 iPad (retina) -->
    <link href="media/images/mobile/icon-152.png" sizes="152x152" rel="apple-touch-icon">
    <!-- iOS 6 iPad (retina) -->
    <link href="media/images/mobile/icon-144.png" sizes="144x144" rel="apple-touch-icon">
    <!-- iOS 7 iPhone (retina) -->
    <link href="media/images/mobile/icon-120.png" sizes="120x120" rel="apple-touch-icon">
    <!-- iOS 6 iPhone (retina) -->
    <link href="media/images/mobile/icon-114.png" sizes="114x114" rel="apple-touch-icon">
    <!-- iOS 7 iPad -->
    <link href="media/images/mobile/icon-76.png" sizes="76x76" rel="apple-touch-icon">
    <!-- iOS 6 iPad -->
    <link href="media/images/mobile/icon-72.png" sizes="72x72" rel="apple-touch-icon">
    <!-- iOS 6 iPhone -->
    <link href="media/images/mobile/icon-57.png" sizes="57x57" rel="apple-touch-icon">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">


    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=visualization"></script>
    <script src='https://cdn.firebase.com/js/client/1.1.1/firebase.js'></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="/media/css/mobile/main.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="/media/css/mobile/framework7.min.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="/media/css/mobile/framework7.themes.min.css" media="screen"/>


    <script src="/media/js/mobile/framework7.min.js"></script>

    <script src="/media/js/mobile/heat.map.js"></script>
    <script src="/media/js/mobile/main.js"></script>
</head>
<body>