<div class="top-main-screen">
    <span class="refresh-btn" onClick="javascript:initializeCurrentLocation();"></span>
    <div class="refresh-btn-loading" style="display: none;">
        <div class="double-bounce1"></div>
        <div class="double-bounce2"></div>
    </div>
</div>
<div class="main-screen">
    <button id="button-awesome" class="awesome-btn"  style="display: none;">AWESOME</button>
</div>