<!-- TUTORIAL -->
<div class="tutorial">
    <ul class = "bxslider">
        <li>
            <div class = "tutorial-slide-1">
                <a href="#" class="close-tutorial-button"></a>
                <p>First Slide<br><br><br>
                 <span>“I think you will find/When your death takes its toll/All the money you made/Will never buy back your soul…”
                </span>
                </p></div>
        </li>
        <li>
            <div class = "tutorial-slide-2">
                <a href="#" class="close-tutorial-button"></a>
                <p>Second Slide<br><br><br>
                   <span>“Take a sad song, and make it better…”</span></p></div>
        </li>
        <li>
            <div class = "tutorial-slide-3">
                <a href="#" class="close-tutorial-button"></a>
                <p>Third Slide<br><br><br>
                   <span>There’s someone for me somewhere/And I still miss someone…”</span></p>
            </div>
        </li>

    </ul>
</div>