<!-- TUTORIAL -->
<div class = "tutorial">
    <ul class = "bxslider">

        <li>
            <div class=first-slider>
                <img src="media/images/mobile/img-slide01.png" width="225" height="271"/>
                <p>Spread awesomeness in the city by marking your location when partying hard!</p>
            </div>
        </li>
        <li>
            <div class="second-slider">
                <img src="media/images/mobile/img-slide02.png" width="225" height="271"/>
                <p>FIND AWESOMENESS: See all the hot spots on the map in real time. </p>
            </div>
        </li>
        <li>
            <div class="third-slider">
                <a href="#tutorial" class="close-tutorial-button">
                    <img src="media/images/mobile/img-slide03.png" width="225" height="271"/>
                </a>
                <p>SPREAD AWESOME / FIND AWESOME</p>
            </div>
        </li>

    </ul>
</div>