<!-- TUTORIAL -->
<div class = "tutorial">
    <ul class = "bxslider">

        <li>
            <div>
                <a href = "#tutorial" class = "close-tutorial-button"></a>

                <p>Spread awesomeness in the city by marking your location when partying hard!</p></div>
        </li>
        <li>
            <div>
                <a href = "#tutorial" class = "close-tutorial-button"></a>

                <p>FIND AWESOMENESS: SEE all the hot spots on the map in real time. </p>
            </div>
        </li>
        <li>
            <div>
                <a href = "#tutorial" class = "close-tutorial-button"></a>

                <p>SPREAD AWESOME / FIND AWESOME</p></div>
        </li>

    </ul>
</div>