<?php $app->render('mobile/partials/head-includes.phtml') ?>

<div class="wrapper">
    <div id="map-canvas"></div>
</div>

<!-- Mobile Pages -->
<?php $app->render('mobile/partials/pages/loading-screen.phtml'); ?>
<?php $app->render('mobile/partials/pages/tutorial-slider.phtml'); ?>
<?php $app->render('mobile/partials/pages/main-screen.phtml'); ?>
<?php $app->render('mobile/partials/pages/success-screen.phtml'); ?>

<?php $app->render('mobile/partials/footer-includes.phtml'); ?>